In [2]:
import os
from typing import List, Dict


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
original_data = pd.read_pickle("../data/processed/eeg_processed.pkl")

In [4]:
filter_data = pd.read_pickle("../data/processed/eeg_processed_X_train.pkl")

In [11]:
pd.merge(filter_data[["subject", "trial", "trail_type", "epoch_data_ICA"]], original_data[["subject", "trial", "trail_type", "label_description"]], how= "left", 
         left_on= ["subject", "trial", "trail_type"],
         right_on=["subject", "trial", "trail_type"])

,subject,trial,trail_type,epoch_data_ICA,label_description
0,S070,11,motor,"[[-1.1368011378190781e-15, 0.1634164292161687,...",rest
1,S070,11,motor,"[[-1.1368011378190781e-15, 0.1634164292161687,...",left_fist
2,S070,11,motor,"[[-1.1368011378190781e-15, 0.1634164292161687,...",rest
3,S070,11,motor,"[[-1.1368011378190781e-15, 0.1634164292161687,...",right_fist
4,S070,11,motor,"[[-1.1368011378190781e-15, 0.1634164292161687,...",rest
...,...,...,...,...,...
825412,S001,8,imaginary,"[[1.3399577791515012e-15, 0.9239857844560102, ...",right_fist
825413,S001,8,imaginary,"[[1.3399577791515012e-15, 0.9239857844560102, ...",rest
825414,S001,8,imaginary,"[[1.3399577791515012e-15, 0.9239857844560102, ...",left_fist
825415,S001,8,imaginary,"[[1.3399577791515012e-15, 0.9239857844560102, ...",rest
825416,S001,8,imaginary,"[[1.3399577791515012e-15, 0.9239857844560102, ...",left_fist

In [24]:
a = original_data.drop("epoch_data", axis = 1).groupby(["subject", "trial", "trail_type", "label_description"]).count().reset_index()

In [31]:
original_data.drop("epoch_data", axis = 1).groupby(["subject", "trial", "trail_type", "label_description", "label"]).value_counts()

subject  trial  trail_type  label_description  label
S001     1      baseline    rest               T0        1
         2      baseline    rest               T0        1
         3      motor       left_fist          T1        8
                            rest               T0       15
                            right_fist         T2        7
                                                        ..
S109     13     motor       both_fist          T1        8
                            rest               T0       15
         14     imaginary   bot_feet           T2        8
                            both_fist          T1        7
                            rest               T0       15
Name: count, Length: 4144, dtype: int64

In [35]:
original_data[(original_data["subject"]=="S001") & (original_data["trail_type"]=="motor") & (original_data["label_description"]== "rest")]

,subject,trial,trail_type,epoch_data,label,label_description
2,S001,3,motor,"[[-5.6999999999999996e-05, -4.9e-05, -5.499999...",T0,rest
4,S001,3,motor,"[[-3.7e-05, -1.1e-05, -7e-06, 2e-06, 1.8e-05, ...",T0,rest
6,S001,3,motor,"[[7.3e-05, 4.4999999999999996e-05, 4.2e-05, -1...",T0,rest
8,S001,3,motor,"[[2.7e-05, 3.7e-05, 5.4999999999999995e-05, 8....",T0,rest
10,S001,3,motor,"[[-3.5e-05, -3.7e-05, -1.9999999999999998e-05,...",T0,rest
...,...,...,...,...,...,...
322,S001,13,motor,"[[-3.6e-05, -3.2999999999999996e-05, -1.899999...",T0,rest
324,S001,13,motor,"[[-1.9999999999999998e-05, -2.9e-05, -2.1e-05,...",T0,rest
326,S001,13,motor,"[[7.999999999999999e-05, 6.2e-05, 5.2e-05, 5.2...",T0,rest
328,S001,13,motor,"[[3.7999999999999995e-05, 2.1e-05, 1.999999999...",T0,rest
330,S001,13,motor,"[[4.9999999999999996e-06, -1.2e-05, -4.4e-05, ...",T0,rest

In [7]:
original_data.columns

Index(['subject', 'trial', 'trail_type', 'epoch_data', 'label',
       'label_description'],
      dtype='object')

In [10]:
filter_data.columns

Index(['subject', 'trial', 'trail_type', 'epoch_data', 'shape',
       'epoch_data_normalized', 'epoch_data_bandpass', 'epoch_data_ICA'],
      dtype='object')

In [12]:
original_data.shape

(39569, 6)

In [13]:
filter_data.shape

(27547, 8)